name: Upload schema to Apollo

on:
  push:
    branches:
      - master
    paths:
      - 'schema.graphql'

jobs:
  upload:
    runs-on: ubuntu-latest
    container: 
      image: node:lts

    steps:
    - uses: actions/checkout@v1

    - name: Create clean schema
      run: |
        cat schema.graphql | awk '{sub(/ @aws_cognito_user_pools/,"")}1' | awk '{sub(/ @aws_api_key/,"")}1' > schema_public.graphql
        cat schema_public.graphql

    - name: Push schema to Apollo
      env:
        APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
        APOLLO_KEY_TEST: ${{ secrets.APOLLO_KEY_TEST }}
        APOLLO_KEY_STAGE: ${{ secrets.APOLLO_KEY_STAGE }}
      run: |
        npx apollo service:push --graph=tifo-api-dev --key=$APOLLO_KEY --variant=current --localSchemaFile=schema_public.graphql
        npx apollo service:push --graph=tifo-api-test --key=$APOLLO_KEY_TEST --variant=current --localSchemaFile=schema_public.graphql
        npx apollo service:push --graph=tifo-api-stage --key=$APOLLO_KEY_STAGE --variant=current --localSchemaFile=schema_public.graphql